# Generated by Django 4.0.2 on 2022-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('price', models.SmallIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=30)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
