# Generated by Django 4.0.2 on 2022-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('price', models.SmallIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=30)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='address',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='author',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='price',
        ),
    ]
