# Generated by Django 4.0.2 on 2022-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ads_id_alter_categories_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
